blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/edit/<int:pk>', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/publish/<int:pk>', views.post_publish, name='post_publish'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/add_comment/', views.post_add_comment, name='post_add_comment'),
    path('post/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('post/<int:pk>/remove/comment', views.comment_remove, name='comment_remove'),
    path('registration/', views.registration, name='registration'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def posted_post(self):
        return self.posts.filter(published_date__lte=timezone.now()).order_by('published_date')


class Post(models.Model):
    TO_DO = 'TO_DO'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    BLOCK = 'BLOCK'
    STATUS = (
        (TO_DO, "TO DO"),
        (IN_PROGRESS, "IN PROGRESS"),
        (COMPLETED, "COMPLETED"),
        (BLOCK, "BLOCK")
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.ForeignKey(Category, related_name='posts', null=True, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS, default=TO_DO)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post, Comment, Profile


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'image', 'status')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

blog/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Profile, Category
from django.utils import timezone
from .forms import PostForm, CommentForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')

    if request.method == "POST":
        searched_post = request.POST.get('name', None)
        if searched_post:
            posts = posts.filter(title__contains=searched_post)
    else:
        category_id = request.GET.get('category_id', None)
        if category_id:
            posts = posts.filter(category_id=category_id)

    return render(request, 'blog/post_list.html', {"posts": posts})


def post_detail(request, pk):
    try:
        post = Post.objects.get(id=pk)
    except ObjectDoesNotExist:
        #TODO return custom 404 page
        raise Http404("object not found")

    return render(request, 'blog/post_detail.html', {'post': post})


@login_required
def post_new(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.category = Category.objects.get(pk=request.POST.get("category"))
            post.save()
            return redirect('post_detail', pk=post.pk)
        else:
            return render(request, 'blog/post_edit.html', {'form': form, 'categories': categories, 'statuses': Post.STATUS})

    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form, 'categories': categories})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            image = request.FILES.get("image", None)
            post.image = image if image else post.image
            post.author = request.user
            post.category = Category.objects.get(pk=request.POST.get("category"))
            post.save()
            return redirect('post_detail', pk=post.pk)
        else:
            return render(request, 'blog/post_edit.html', {'form': form, 'categories': categories})
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form, 'categories': categories})


@login_required
def post_draft_list(request):
    drafts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'drafts':drafts})


@login_required
def post_publish(request, pk):
    published_post = Post.objects.get(id=pk)
    published_post.publish()
    return redirect('post_list')


@login_required
def post_remove(request, pk):
    removed_post = get_object_or_404(Post, id=pk)
    removed_post.delete()
    return redirect('post_list')


def post_add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('post_detail', pk=pk)
        else:
            return render(request, "blog/post_add_comment.html", {"form": form})
    else:
        form = CommentForm()
        return render(request, "blog/post_add_comment.html", {"form": form})


def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)


def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.is_active = True
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request, "registration/register_done.html", {'new_user': new_user})
        else:
            return render(request, "registration/registration.html", {'form': form})
    else:
        form = UserRegistrationForm()
        return render(request, 'registration/registration.html', {'form': form})


@login_required
def edit_profile(request):
    user = request.user
    if request.method == "POST":
        profile_form = ProfileEditForm(request.POST, instance=user.profile)
        user_form = UserEditForm(request.POST, instance=user)
        if profile_form.is_valid() and user_form.is_valid():
            photo = request.FILES.get('photo', None)
            profile_form.instance.photo = photo if photo else profile_form.instance.photo
            profile_form.save()
            user_form.save()
            return redirect('edit_profile')
        else:
            return render(
                request,
                'registration/profile_edit.html',
                {'user_form': user_form, 'profile_form': profile_form}
            )
    else:
        user_form = UserEditForm(instance=user)
        profile_form = ProfileEditForm(instance=user.profile)
    return render(
        request,
        'registration/profile_edit.html',
        {'user_form': user_form, 'profile_form': profile_form}
    )

blog/templates/blog/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Literary blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Slab:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>

    <div class="page-header">
    <div class="topnav">

    </div>
        {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
            <a href="{% url 'logout' %}" class="top-menu"><span class="glyphicon glyphicon-log-out"></span></a>
            <a href="{% url 'edit_profile' %}" class="top-menu"> Hello {{ user.username }}</a>

        {% else %}
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-log-in"></span></a>
        {% endif %}
        <h1><a class="logo" href="/">ToDo</a></h1>
        <form method="post" action="{% url 'post_list' %}">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Search...">

                <button type="submit" class="glyphicon glyphicon-search"></button>
        </form>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        {{ categories_html }}
        </div>
    </div>
</body>
</html>

blog/templates/blog/categories.html
<div class="col-md-4 categories">
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'post_list' %}?category_id={{ category.id }}">{{ category.name }} ({{ category.posted_post.count }})</a></li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_add_comment.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Sent</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'post_publish' pk=post.pk %}"><span class="glyphicon glyphicon-share-alt"></span></a>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-trash"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
            <h4>Status: {{ post.get_status_display }}</h4>
        <p>{{ post.text|linebreaksbr }}</p>

    </div>
    <hr>
    {% if user.is_authenticated %}
    <a class="btn btn-default" href="{% url 'post_add_comment' pk=post.pk %}">Add comment</a>
    {% endif %}
    {% if post.comments.all %}
        {% for comment in post.comments.all %}
            <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            <div class="comment">
                <div class="date">{{ comment.created_date }}</div>
                <strong>{{ comment.author }}</strong>
                <p>{{ comment.text|linebreaks }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p> No comments here yet :( </p>
    {% endif %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for draft in drafts %}
        <div class="post">
            <div class="date">
                {{ draft.created_date }}
            </div>
            <h1><a href="{% url 'post_detail' pk=draft.pk %}">{{ draft.title }}</a></h1>
            <p>{{ draft.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New task</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.title.errors }}
            <label for="id_title">Title </label>
            <div>
                <input type="text" name="title" value="{{ form.instance.title }}" maxlength="100"
                       class="textinput textInput form-control" id="id_title">
            </div>
        </div>
        <div class="form-group">
            {{ form.text.errors }}
            <label for="id_text">Text</label>
            <div>
                <input type="text" name="text" value="{{ form.instance.text }}" maxlength="500"
                class="textinput textInput form-control" id="id_text">
            </div>
        </div>
        <div class="form-group">
            {{ form.text.errors }}
            <label for="id_text" >Category</label>
            <select name="category" id="categories" class="form-control">

                {% for category in categories %}
                    <option {% if form.instance.category == category%}selected{% endif %}
                            value="{{ category.id }}"> {{ category.name }} </option>
                {% endfor %}
            </select>
        </div>
         <div class="form-group">
            {{ form.status.errors }}
            <label for="id_text" >Status</label>

                {{ form.status }}
        </div>
        <div class="form-group">
            {{ form.image.errors }}
            <label for="id_image">Image</label>
            <div>
                {% if form.instance.image %}
                    <img width="200" src="{{ form.instance.image.url }}">
                {% endif %}
                <input type="file" name="image" id="id_image">
            </div>

        </div>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                            <h4>
                    Status: {{ post.get_status_display }}
                </h4>
            <p>{{ post.text|linebreaksbr }}</p>
            <div class="date">
                Created {{ post.published_date }} by {{ post.author }}
            </div>

            <a href="{% url 'post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
        </div>
    {% endfor %}
{% endblock %}